message(STATUS "Detected processor: ${CMAKE_SYSTEM_PROCESSOR}")

if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
    message(STATUS "Target: ARM — enabling NEON via -march=native")
    set(VECTORDB_ARCH "arm" CACHE STRING "Target architecture" FORCE)
    add_compile_options(-march=native)
    add_compile_definitions(VECTORDB_ARCH_ARM)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
    message(STATUS "Target: x86 — enabling AVX2 + FMA")
    set(VECTORDB_ARCH "x86" CACHE STRING "Target architecture" FORCE)
    add_compile_options(-mavx2 -mfma)
    add_compile_definitions(VECTORDB_ARCH_X86)
else()
    message(WARNING "Unknown arch '${CMAKE_SYSTEM_PROCESSOR}' — scalar fallback only")
    set(VECTORDB_ARCH "generic" CACHE STRING "Target architecture" FORCE)
endif()
